---
title: 'Learning Balto-Finnic dialects'
author: "Kaili Vesik"
date: '2023-11-21'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
# don't show this output
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

We begin by setting options (output not shown) and loading the appropriate libraries.


```{r load}
# for data wrangling
library(tidyverse)
# for plotting
library(ggplot2)
library(ggbeeswarm)
library(vipor)
library(viridis)
library(ggstance)
library(ggrepel)
library(scales)
```

## Constraint set

Create the vectors containing the faithfulness and (many) markedness constraint names.

```{r constraintnames}
identcons <- c("IdBkSyl1", "IdBk")
maxcons <- c("MaxSyl1", "Max")
nonempty <- c("NonEmpty")

frontsets <- c("F1", "F3", "F4", "F5")
backsets <- c("B1", "B2", "B3", "B5")
starfronts <- paste("star", frontsets, sep="")
starbacks <- paste("star", backsets, sep="")

starfrontbacks <- c()
starbackfronts <- c()
for (fr in frontsets) {
  for (bk in backsets) {
    starfrontbacks <- c(starfrontbacks, paste(fr, bk, sep=""), paste(fr, bk, sep="_"))
    starbackfronts <- c(starbackfronts, paste(bk, fr, sep=""), paste(bk, fr, sep="_"))
  }
}
starfrontbacks <- paste("star", starfrontbacks, sep="")
starbackfronts <- paste("star", starbackfronts, sep="")
```


## Data

We load the data from file, and omit columns irrelevant to this analysis.

```{r data}

numoutin <- c("trialnum", "generated", "heard")

identconswchanges <- paste0(rep(identcons, each=2), c("_change", ""))
maxconswchanges <- paste0(rep(maxcons, each=2), c("_change", ""))
nonemptywchanges <- paste0(rep(nonempty, each=2), c("_change", ""))
starfrontswchanges <- paste0(rep(starfronts, each=2), c("_change", ""))
starbackswchanges <- paste0(rep(starbacks, each=2), c("_change", ""))
starfrontbackswchanges <- paste0(rep(starfrontbacks, each=2), c("_change", ""))
starbackfrontswchanges <- paste0(rep(starbackfronts, each=2), c("_change", ""))

# append different combinations of column titles for different types of simulations
coltitlesall_max0nonempty0 <- c(numoutin, identconswchanges, starfrontswchanges, starbackswchanges, starfrontbackswchanges, starbackfrontswchanges)
coltitlesall_max1nonempty0 <- c(numoutin, identconswchanges, maxconswchanges, starfrontswchanges, starbackswchanges, starfrontbackswchanges, starbackfrontswchanges)
coltitlesall_max1nonempty1 <- c(numoutin, identconswchanges, maxconswchanges, nonemptywchanges, starfrontswchanges, starbackswchanges, starfrontbackswchanges, starbackfrontswchanges)

# select different combinations of columns for different types of simulations
coltitlestoselect_max0nonempty0 <- c("trialnum", identcons, starfronts, starbacks, starfrontbacks, starbackfronts)
coltitlestoselect_max1nonempty0 <- c("trialnum", identcons, maxcons, starfronts, starbacks, starfrontbacks, starbackfronts)
coltitlestoselect_max1nonempty1 <- c("trialnum", identcons, maxcons, nonempty, starfronts, starbacks, starfrontbacks, starbackfronts)


prepare_data <- function(filename) {
  if (!grepl("wdel", filename)) {
    coltitlesall <- coltitlesall_max0nonempty0
    coltitlestoselect <- coltitlestoselect_max0nonempty0
  } else if (grepl("prs", filename)) {
    coltitlesall <- coltitlesall_max1nonempty1
    coltitlestoselect <- coltitlestoselect_max1nonempty1
  } else {
    coltitlesall <- coltitlesall_max1nonempty0
    coltitlestoselect <- coltitlestoselect_max1nonempty0
  }
  
  # load data from file, name columns, remove unwanted columns
  df <- read_tsv(paste0("..\\simulation_outputs\\",filename), 
                 col_types = list(
                   trialnum = col_integer(),
                   generated = col_character(),
                   heard = col_character(),
                   .default = col_double()))

  colnames(df) <- coltitlesall
  df <- 
    df %>%
    select(all_of(coltitlestoselect))
  
  # fill in missing data and adjust trial number for initial state
  df <- 
    df %>%
    fill(all_of(coltitlestoselect)) %>%
    fill(all_of(coltitlestoselect), .direction = "up")
  df$trialnum[1] <- 0

  
  
  # just keep the last entry for each trial number 
  # (so, after both the learning adjustment and a possible a priori ranking adjustment)
  df <-
    df %>%
    arrange(trialnum) %>%
    group_by(trialnum) %>% 
    summarise_all(last) %>%
    ungroup() %>%
    arrange(trialnum)
  
  # pivot from wide to long, so we don't have a separate column for each constraint
  df <-
    df %>% 
    pivot_longer(!trialnum, names_to="constraint", values_to="value")
  
  finalvalues <- df %>% 
    group_by(constraint) %>% 
    top_n(1, trialnum) %>%
    pull(value) %>%
    round(digits=2)
  
  constraint_levels <- coltitlestoselect
  constraint_labels <- constraint_levels # TODO for now...
  # constraint_labels <- c("*F", "*ɤ", "*e", "Id-Syl1(Bk)", "Id(Bk)", "Agr(Bk)", "GMH(F)", "GMH(ɤ)", "GMH(e)")
  
  constraint_labelswithvalues <- paste(constraint_labels, "→", finalvalues)
  df$constraint <- factor(df$constraint, levels=constraint_levels, labels=constraint_labelswithvalues)
   
  return(df)
}

plot_trajectories <- function(df, lang, trialsperbatch, experimentnum) {

  trajectoryplot <-
    ggplot(data=df, mapping=aes(x=trialnum, y=value)) +
    geom_line(aes(color=fct_reorder2(constraint, trialnum, value, .fun = last2)), size=0.6, show.legend=FALSE) +  # can replace all the fct business with just "constraint"
    ggtitle(paste0(lang, " learning trajectories over 4x", trialsperbatch, " trials (exp ", experimentnum, ")")) +
    theme(axis.text=element_text(size=11, colour="black"),
        plot.title = element_text(hjust = 0.5),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
    labs(y= "Constraint value", x = "Learning trial #") +
    scale_color_viridis_d(name = "constraint") +
    scale_x_continuous(trans="log10", labels=comma_format(accuracy=1)) +
    scale_y_continuous(limits=c(0,115), breaks=seq(from=0, to=110, by=10))
    # scale_y_continuous(sec.axis = sec_axis(~ ., breaks = data_ends2)) +
  # geom_text_repel(
  #   aes(label = constraint), data = data_ends, 
  #   size = 3
  #   )
    
  print(trajectoryplot)
}

extract_langtrialsexpnum <- function(filename) {
  filename_levels <- str_split_1(filename, "\\\\")
  num_levels <- length(filename_levels)
  filename_only <- filename_levels[num_levels]
  containing_folder <- filename_levels[num_levels-1]
  
  if (grepl("FullHistory_fixed", filename_only)) {
    # output is from OTSoft
    langstring <- substr(containing_folder, 1, 2)
    expnumstring <- substr(containing_folder, 3, 5)
  } else {
    # output is from my Python script
    langstring <- substr(filename_only, 1, 2)
    expnumstring <- substr(filename_only, 3, 5)
  }
  trialsstring <- switch(
    strtoi(substr(expnumstring, 3, 3)),
    "100",
    "500",
    "1000",
    "5000",
    "10000"
  )
  print(langstring)
  print(trialsstring)
  print(expnumstring)
  return(c(langstring, trialsstring, expnumstring))
}

makeplot <- function(filename) {
  info <- extract_langtrialsexpnum(filename)
  lang <- info[1]
  trials <- info[2]
  expnum <- info[3]
  print(lang)
  print(trials)
  print(expnum)
  df <- prepare_data(filename)
  plot_trajectories(df, lang, trials, expnum)
}

historyfiles <- c(
  # "TODO",
  # "K413p_OT_Soft_KE_iFBfb_forGLA_cat_starBQP2cons_no2xcounts_HISTORY1000_forR.txt",
  # "K414p_OT_Soft_KE_iFBfb_forGLA_cat_starBQP2cons_no2xcounts_HISTORY5000_forR.txt",
  # "K415p_OT_Soft_KE_iFBfb_forGLA_cat_starBQP2cons_no2xcounts_HISTORY50000_forR.txt",
  # "K416p_OT_Soft_KE_iFBfb_forGLA_cat_starBQP2cons_no2xcounts_HISTORY500000_forR.txt",
  # "S413p_OT_Soft_SE_iFBfb_forGLA_cat_starBQP2cons_no2xcounts_HISTORY1000_forR.txt",
  # "S414p_OT_Soft_SE_iFBfb_forGLA_cat_starBQP2cons_no2xcounts_HISTORY5000_forR.txt",
  # "S415p_OT_Soft_SE_iFBfb_forGLA_cat_starBQP2cons_no2xcounts_HISTORY50000_forR.txt",
  # "S416p_OT_Soft_SE_iFBfb_forGLA_cat_starBQP2cons_no2xcounts_HISTORY500000_forR.txt",
  # "S315p_OT_Soft_SE_iFBfb_forGLA_cat_QP2cons_no2xcounts_HISTORY50000_forR.txt"
  "20231107_Magri_outputs\\Fi153_python_OTSoft-PDDP-Fin_GLA\\Fi153_OTSoft-PDDP-Fin_GLA_HISTORY1000_forR.txt",
  "20231107_Magri_outputs\\NE153_python_OTSoft-PDDP-NEst_GLA\\NE153_OTSoft-PDDP-NEst_GLA_HISTORY1000_forR.txt"
)

for (hfile in historyfiles) {
  makeplot(hfile)
}



```

```{r}
numsamples <- 100000

for (dif in 1:20) {
  if (dif == 1) {
    print(numsamples)
  }
  # make a distribution with mean 0 and SD 2
  # make another one with mean dif and SD 2
  # take a bunch of samples from each
  # dif <- 2
  lowersamples <- rnorm(numsamples, mean=0, sd=2)
  uppersamples1 <- rnorm(numsamples, mean=dif, sd=2)
  uppersamples2 <- rnorm(numsamples, mean=dif, sd=2)
  # print(mean(lowersamples))
  # print(mean(uppersamples))
  
  # for each pair of samples, determine which distribution has the higher value
  # determine whether at least one of the upper samples flipped with lowersamples
  didtheyflip <- (lowersamples > uppersamples1) | (lowersamples > uppersamples2)
  meanflips <- mean(didtheyflip)
  # print(meanflips)
  
  # calculate the probability of the distr with the lower mean ending up with the higher value
  print(sprintf("%s %i %s %f", "for a difference of", dif, "the chance of flipping order is", meanflips))
  
}

```

